# Generated by Django 4.2.13 on 2026-02-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_checklisttemplate_expensecategory_translationkey_and_more'),
    ]

    operations = [
    ]
